In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

type(mylist)

list

In [6]:
arr = np.array(mylist)
arr

array([1, 2, 3])

In [9]:
type(mylist)

list

In [8]:
type(arr)

numpy.ndarray

In [12]:
# Nested list

mylist = [[1,2,3],[4,5,6],[7,8,9]]

mymatrix = np.array(mylist)

In [19]:
mymatrix.shape

(3, 3)

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.zeros((5,5),dtype="int64")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
np.ones((3,3),dtype="int") + 4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.ones(4,dtype="int") * 100

array([100, 100, 100, 100])

In [33]:
[1,1,1,1] *2

[1, 1, 1, 1, 1, 1, 1, 1]

In [39]:
np.ones(4,dtype="int")%3

array([1, 1, 1, 1])

In [47]:
np.eye(2,dtype="int")

array([[1, 0],
       [0, 1]])

In [48]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Creating Random numbers in Numpy

In [52]:
np.random.rand(3,2)

array([[0.56045595, 0.88876748],
       [0.9848287 , 0.78467335],
       [0.90911119, 0.96904591]])

In [54]:
np.random.randn(2)

array([-0.23822818, -0.64086528])

In [57]:
np.random.normal(0,1,(2,2))

array([[ 0.6260633 ,  0.57566513],
       [-1.33703404, -0.28633628]])

In [62]:
np.random.randint(1,100)

54

In [84]:
np.random.uniform(0,0,(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.random.seed(555)

np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [97]:
np.random.rand(4)

array([0.14859311, 0.81086617, 0.65310538, 0.54446869])

In [98]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [121]:
arr = np.random.randint(0,3,20)
arr

array([2, 2, 0, 0, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1])

In [120]:
arr.resize(4,5)
arr

array([[1, 2, 1, 1, 2],
       [0, 2, 2, 2, 1],
       [1, 0, 0, 2, 0],
       [2, 0, 0, 1, 1]])

In [119]:
arr.reshape(5,4)

array([[1, 2, 1, 1],
       [2, 0, 2, 2],
       [2, 1, 1, 0],
       [0, 2, 0, 2],
       [0, 0, 1, 1]])

In [123]:
randArr = np.random.randint(0,50,20)
randArr

array([26, 46, 46,  5,  1, 40, 27, 20, 48,  0, 29, 41, 25, 44, 46, 48, 11,
        2, 26, 36])

In [124]:
randArr.max()

48

In [125]:
randArr.min()

0

In [127]:
randArr.argmax()

8

In [128]:
randArr.argmin()

9

In [130]:
randArr.dtype

dtype('int64')

### Numpy Index Selection

In [132]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr[8]

8

In [136]:
arr[1:5]

array([1, 2, 3, 4])

In [137]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [138]:
arr[:5]

array([0, 1, 2, 3, 4])

In [139]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [140]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [144]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [150]:
(arr**(0.5)).dtype

AttributeError: 'float' object has no attribute 'dtype'

In [151]:
arr.dtype

dtype('int64')

In [157]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [154]:
slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [155]:
slice_of_arr[:] = 99

In [156]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [158]:
arr_copy = arr.copy()

In [162]:
arr_copy[0:4] = -1

print(arr_copy,"\n",arr)

[-1 -1 -1 -1 99 99  6  7  8  9 10] 
 [99 99 99 99 99 99  6  7  8  9 10]


### INDEXING on 2D array

In [181]:
arr_2d = np.random.randint(0,50,(3,3))
arr_2d

array([[20, 49, 23],
       [13, 29,  2],
       [40,  2, 46]])

In [165]:
arr_2d.shape

(3, 3)

In [193]:
arr_2d[1][2]

2

In [194]:
arr_2d[1]

array([13, 29,  2])

In [204]:
arr_2d[1:]

array([[13, 29,  2],
       [40,  2, 46]])

In [205]:
arr_2d[1:][1:]

array([[40,  2, 46]])

In [182]:
arr_2d[:2][1:]

array([[20, 49, 23],
       [13, 29,  2]])

In [208]:
arr_2d[:3,1:]

array([[49, 23],
       [29,  2],
       [ 2, 46]])

In [210]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [217]:
bool_arr = arr > 4

In [218]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [222]:
arr1 = arr[arr>4]
arr1

array([ 5,  6,  7,  8,  9, 10])

In [223]:
arr1[arr1<10]

array([5, 6, 7, 8, 9])

## NumPy Operations

In [224]:
import numpy as np

In [226]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [227]:
arr +1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [228]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [229]:
(arr + 2)/100

array([0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12])

In [230]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [233]:
arr / 0

/tmp/ipykernel_9311/3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [236]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [237]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [238]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [239]:
np.sum(arr)

55

In [240]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [241]:
arr.sum()

55

In [242]:
arr.mean()

5.5

In [243]:
arr.max()

10

In [248]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [246]:
arr_2d.shape

(3, 4)

In [254]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [255]:
 arr_2d.sum(axis=1)

array([10, 26, 42])